#!/bin/bash

LOCALDIR=`cd "$( dirname $0 )" && pwd`
cd $LOCALDIR

systemdir=$1

apps_dir="
MiuiCamera
aiasst_service
GoogleContactsSyncAdapter
PhotoTable
talkback
ConfigUpdater
GmsCore
GooglePlayServicesUpdater
QdcmFF
xdivert
EmergencyInfo
GoogleServicesFramework
AiAsstVision
AnalyticsCore
AutoRegistration
BasicDreams
BluetoothMidiService
BookmarkProvider
BTProductionLineTool
BuiltInPrintService
CarrierDefaultApp
CertInstaller
Cit
com.miui.qr
CompanionDeviceManager
com.xiaomi.macro
FidoAuthen
FidoClient
FusedLocationProvider
GooglePrintRecommendationService
Health
HybridAccessory
HybridPlatform
Joyose
Joyose
KeyChain
KSICibaEngine
LiveWallpapersPicker
mab
mi_connect_service
MiDrive
MiLink
MIpay
MiPlayClient
MiuiAudioMonitor
MiuiBugReport
MiuiDaemon
MIUIFrequentPhrase
MIUIgreenguard
MiuiPrintSpoolerBeta
MIUISuperMarket
MIUITouchAssistant
ModemTestBox
MSA
NextPay
NQNfcNci
PacProcessor
PaymentService
PlatformCaptivePortalLogin
PowerChecker
Protips
QColor
SecureElement
SecurityInputMethod
SimAppDialog
SimContact
Stk
SystemHelper
Traceur
TranslationService
TSMClient
Updater
UPTsmService
VoiceAssist
VoiceTrigger
VsimCore
WallpaperBackup
WAPPushManager
WMService
XiaomiModemDebugService
XMCloudEngine
YouDaoEngine
data-app
data-app
auto-install.json
alarms
alarms
Bottle.ogg
Bubble.ogg
Bullfrog.ogg
Burst.ogg
Chirp.ogg
Clank.ogg
Crystal.ogg
FadeIn.ogg
FadeOut.ogg
Flute.ogg
Fresh.ogg
Frog.ogg
Guitar.ogg
Harp.ogg
IncomingMessage.ogg
IncomingMessage.ogg
MessageSent.ogg
MessageSent.ogg
Moment.ogg
Potion.ogg
Radar.ogg
Spring.ogg
Swoosh.ogg
WindChime.ogg
AcousticGuitar.ogg
Candy.ogg
Carousel.ogg
Celesta.ogg
Childhood.ogg
Country.ogg
Cowboy.ogg
Fairyland.ogg
Fantasy.ogg
FieldTrip.ogg
Glee.ogg
IceLatte.ogg
Kungfu.ogg
Lollipop.ogg
MiHouse.ogg
MiJazz.ogg
Orange.ogg
SpaceAge.ogg
ToyRobot.ogg
Vigor.ogg
Africa
AfricaAnimals_preview.ogg
ArcticAnimals_preview.ogg
Australia
AustraliaAnimals_preview.ogg
BirdCicadaNotificationDay1.ogg
BirdCicadaNotificationDay2.ogg
BirdCicadaNotificationDay3.ogg
BirdCicadaNotificationDay4.ogg
BirdCicadaNotificationDay5.ogg
BirdCicadaNotificationDay6.ogg
BirdCicadaNotificationDay7.ogg
BirdCicadaNotificationDay8.ogg
BirdCicadaNotificationEvening1.ogg
BirdCicadaNotificationEvening2.ogg
BirdCicadaNotificationEvening3.ogg
BirdCicadaNotificationEvening4.ogg
BirdCicadaNotificationEvening5.ogg
BirdCicadaNotificationMidday1.ogg
BirdCicadaNotificationMidday2.ogg
BirdCicadaNotificationMidday3.ogg
BirdCicadaNotificationNight1.ogg
BirdCicadaNotificationNight2.ogg
BirdCicadaNotificationSeqDayNight1.ogg
BirdCicadaNotificationSeqDayNight2.ogg
BirdCicada_preview.ogg
Bird_Notification_1.ogg
Bird_Notification_2.ogg
Cicada_Notification_1.ogg
Cicada_Notification_2.ogg
flashlight.ogg
HeiHei.mp3
MIUI_Ringtone_Special_Service.ogg
PolarRegion
bootaudio.mp3
gadgets
miui_mod_icons
wallpaper_group
BlockedNumberProvider
Browser
DMRegService
dpmserviceapp
DynamicSystemInstallationService
ManagedProvisioning
MiGameCenterSDKService
Mirror
MIService
MIUIContentExtension
MIUIMusic
MIUIPersonalAssistant
MIUIQuickSearchBox
MIUIVideo
MIUIYellowPage
MusicFX
ONS
OriginalInstaller
PlatformNetworkPermissionConfig
ProxyHandler
Tag
UserDictionaryProvider
datastatusnotification
PowerOffAlarm
notifications
notifications
ringtones
ringtones
GoogleOneTimeInitializer
seccamservice
DeviceInfo
WfdService
verity_key
CACertService
CneApp
EidService
MiGameService
spk_cal_pinknoise.wav
spk_cal_silence.wav
spk_cal_whitenoise.wav
spk.wav
test.wav
recovery-from-boot.p
"

for delete_dir in $apps_dir ;do
  find $systemdir -type d -name "$delete_dir" | xargs rm -rf
done

rm -rf $1/data-app/*